"""Optional real software-TPM quote to direct core redemption experiment.

This isolated profile does not change the HTTP services' development assurance.
The test CA enrolls an AK generated by the disposable simulator. No manufacturer
provenance, holder-key residency, co-location, or PCR-selection appraisal is
claimed. It uses the released verifier without implementing a TPM wire parser.
"""

from __future__ import annotations

import hashlib
import json
import os
import secrets
import shutil
import subprocess  # nosec B404
import tempfile
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import rfc8785
from agent_manifest import verify_tpm_quote
from cryptography import x509
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.x509.oid import NameOID

from fixtures.registration import create_development_attestation, generate_registration_fixture
from resource_bound_authorization.errors import AuthorizationError
from resource_bound_authorization.issuance import issue_capability
from resource_bound_authorization.models import IssuancePolicy, PrincipalBinding, ResourcePolicy
from resource_bound_authorization.redemption import (
    RedemptionStore,
    create_invocation,
    redeem_capability,
)
from resource_bound_authorization.signatures import public_key_hex
from resource_bound_authorization.verification import (
    verify_development_attestation,
    verify_registered_manifest,
)

_COMMANDS = frozenset(
    {
        "tpm2_createak",
        "tpm2_createek",
        "tpm2_flushcontext",
        "tpm2_pcrextend",
        "tpm2_pcrreset",
        "tpm2_quote",
    }
)
_PROFILE_EVENT = hashlib.sha256(b"resource-bound-authorization:software-tpm-profile:v1").digest()
_EXPECTED_PCR = hashlib.sha256(bytes(32) + _PROFILE_EVENT).digest()
_EXPECTED_COMPOSITE = hashlib.sha256(_EXPECTED_PCR).digest()


def _invoke_tool(interface: str, command: str, *arguments: str, check: bool = True) -> None:
    if command not in _COMMANDS:
        raise ValueError("unrecognized software TPM verification command")
    executable = shutil.which(command)
    if executable is None:
        raise RuntimeError(f"required software TPM command is unavailable: {command}")
    environment = {**os.environ, "TPM2TOOLS_TCTI": interface}
    # Only the fixed tool allowlist is executable; arguments are passed without a shell.
    subprocess.run(  # noqa: S603  # nosec B603
        [executable, *arguments],
        env=environment,
        check=check,
        capture_output=True,
        timeout=20,
    )


def _key_usage(*, certificate_authority: bool) -> x509.KeyUsage:
    return x509.KeyUsage(
        digital_signature=not certificate_authority,
        content_commitment=False,
        key_encipherment=False,
        data_encipherment=False,
        key_agreement=False,
        key_cert_sign=certificate_authority,
        crl_sign=certificate_authority,
        encipher_only=False,
        decipher_only=False,
    )


def _enroll_synthetic_ak(public_pem: bytes, moment: datetime) -> tuple[bytes, bytes]:
    public_key = serialization.load_pem_public_key(public_pem)
    if not isinstance(public_key, rsa.RSAPublicKey):
        raise ValueError("the software TPM fixture requires an RSA AK")
    authority_key = Ed25519PrivateKey.generate()
    authority_name = x509.Name(
        [x509.NameAttribute(NameOID.COMMON_NAME, "Resource Authorization Synthetic Test Authority")]
    )
    root = (
        x509.CertificateBuilder()
        .subject_name(authority_name)
        .issuer_name(authority_name)
        .public_key(authority_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(moment - timedelta(minutes=5))
        .not_valid_after(moment + timedelta(hours=1))
        .add_extension(x509.BasicConstraints(ca=True, path_length=0), critical=True)
        .add_extension(_key_usage(certificate_authority=True), critical=True)
        .sign(authority_key, algorithm=None)
    )
    leaf = (
        x509.CertificateBuilder()
        .subject_name(
            x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "Synthetic software TPM AK")])
        )
        .issuer_name(authority_name)
        .public_key(public_key)
        .serial_number(x509.random_serial_number())
        .not_valid_before(moment - timedelta(minutes=1))
        .not_valid_after(moment + timedelta(minutes=30))
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(_key_usage(certificate_authority=False), critical=True)
        .sign(authority_key, algorithm=None)
    )
    root_pem = root.public_bytes(serialization.Encoding.PEM)
    return leaf.public_bytes(serialization.Encoding.PEM) + root_pem, root_pem


def _produce_quote(interface: str, directory: Path, qualifying_data: bytes) -> tuple[bytes, ...]:
    """Create and quote a disposable AK; keep all contexts inside a temporary directory."""

    endorsement_context = directory / "endorsement.context"
    attestation_context = directory / "attestation.context"
    public_path = directory / "attestation.public.pem"
    _invoke_tool(interface, "tpm2_flushcontext", "-t", check=False)
    _invoke_tool(interface, "tpm2_pcrreset", "16")
    _invoke_tool(interface, "tpm2_pcrextend", f"16:sha256={_PROFILE_EVENT.hex()}")
    _invoke_tool(
        interface,
        "tpm2_createek",
        "-G",
        "rsa",
        "-c",
        str(endorsement_context),
        "-u",
        str(directory / "endorsement.public"),
    )
    _invoke_tool(
        interface,
        "tpm2_createak",
        "-C",
        str(endorsement_context),
        "-G",
        "rsa",
        "-g",
        "sha256",
        "-s",
        "rsassa",
        "-c",
        str(attestation_context),
        "-u",
        str(public_path),
        "-f",
        "pem",
        "-n",
        str(directory / "attestation.name"),
    )
    # The saved AK context can be reloaded after releasing transient slots.
    _invoke_tool(interface, "tpm2_flushcontext", "-t")
    qualifying_path = directory / "qualifying.bin"
    qualifying_path.write_bytes(qualifying_data)
    quote_path = directory / "quote.attest"
    signature_path = directory / "quote.signature"
    _invoke_tool(
        interface,
        "tpm2_quote",
        "-Q",
        "-c",
        str(attestation_context),
        "-l",
        "sha256:16",
        "-q",
        str(qualifying_path),
        "-g",
        "sha256",
        "-f",
        "tss",
        "-m",
        str(quote_path),
        "-s",
        str(signature_path),
    )
    chain, root = _enroll_synthetic_ak(public_path.read_bytes(), datetime.now(UTC))
    return quote_path.read_bytes(), signature_path.read_bytes(), chain, root


def verify_software_tpm_profile(interface: str) -> dict[str, Any]:
    """Verify a genuine quote and use its fresh binding for one direct redemption."""

    if type(interface) is not str or not interface:
        raise ValueError("a software TPM interface is required")
    calling_fixture = generate_registration_fixture("calling_principal")
    other_fixture = generate_registration_fixture("delegated_principal")
    verify_registered_manifest(calling_fixture.registration)
    now = int(time.time())
    challenge = secrets.token_hex(32)
    transcript: dict[str, Any] = {
        "schema_version": "resource-bound-software-tpm-appraisal/v1",
        "challenge": challenge,
        "principal_identifier": calling_fixture.registration.principal_identifier,
        "holder_public_key": calling_fixture.registration.identity_public_key,
        "manifest_digest": calling_fixture.registration.manifest_digest,
        "expires_at": now + 120,
    }
    qualifying_data = hashlib.sha256(rfc8785.dumps(transcript)).digest()
    with tempfile.TemporaryDirectory(prefix="resource-authorization-software-tpm-") as temporary:
        directory = Path(temporary)
        try:
            quote, signature, chain, root = _produce_quote(interface, directory, qualifying_data)
            verification = verify_tpm_quote(
                quote,
                signature,
                chain,
                trusted_roots_pem=root,
                expected_qualifying_data=qualifying_data,
                expected_pcr_digest=_EXPECTED_COMPOSITE,
            )
            if verification is not True or int(time.time()) >= now + 120:
                raise ValueError(
                    "software TPM appraisal did not verify within its freshness window"
                )
            principal = PrincipalBinding(
                principal_identifier=calling_fixture.registration.principal_identifier,
                manifest_digest=calling_fixture.registration.manifest_digest,
                holder_public_key=calling_fixture.registration.identity_public_key,
                attestation_digest=hashlib.sha256(
                    rfc8785.dumps(
                        {
                            "quote_sha256": hashlib.sha256(quote).hexdigest(),
                            "signature_sha256": hashlib.sha256(signature).hexdigest(),
                            "chain_sha256": hashlib.sha256(chain).hexdigest(),
                            "transcript_sha256": qualifying_data.hex(),
                        }
                    )
                ).hexdigest(),
                assurance="software_tpm",
            )
            other_statement = create_development_attestation(other_fixture, challenge, now + 60)
            other_principal = verify_development_attestation(
                other_fixture.registration,
                other_statement,
                expected_challenge=challenge,
                now=int(time.time()),
            )
            issuer_key = Ed25519PrivateKey.generate()
            policy = IssuancePolicy(
                audience="resource_server",
                object_identifier="reference_record",
                tool_name="object.read",
                arguments={"record_identifier": "reference_record"},
                approved_principals=(principal, other_principal),
            )
            capability = issue_capability(principal, issuer_key, policy)
            resource_policy = ResourcePolicy(
                **policy.model_dump(), issuer_public_key=public_key_hex(issuer_key)
            )
            store = RedemptionStore(directory / "redemption.sqlite")
            request = create_invocation(capability, calling_fixture.holder_private_key)
            redemption = redeem_capability(request, resource_policy, store)
            try:
                redeem_capability(request, resource_policy, store)
            except AuthorizationError as error:
                if str(error) != "capability_already_redeemed":
                    raise
            else:
                raise RuntimeError("repeat redemption unexpectedly succeeded")
            return {
                "profile": "isolated_software_tpm_core_redemption",
                "assurance": principal.assurance,
                "manifest_verified": True,
                "quote_verified": True,
                "synthetic_enrollment": True,
                "http_services_integrated": False,
                "attestation_digest": principal.attestation_digest,
                "redemption": "accepted",
                "object_identifier": redemption.object_identifier,
                "repeat_redemption": "rejected",
            }
        finally:
            _invoke_tool(interface, "tpm2_flushcontext", "-t", check=False)


def main() -> None:
    interface = os.environ.get("RESOURCE_AUTHORIZATION_TPM_INTERFACE")
    if interface is None:
        raise SystemExit("RESOURCE_AUTHORIZATION_TPM_INTERFACE is required")
    print(json.dumps(verify_software_tpm_profile(interface), sort_keys=True))


if __name__ == "__main__":
    main()
